# Builtin commands

[[commands]]

template = "grep [_OPTIONS_] _PATTERN_ _PATH_"
description = "Find lines in a file (*grep*)"

groups.PATTERN.expect = "string"
groups.PATH.expect = "path"
groups.OPTIONS.flags = [
  { template = "-i", description = "Case insensitive matching" },
  { template = "-v", description = "Invert match (return non-matching lines)" },
  { template = "*-A* _NUM_", description = "Print _NUM_ lines after the matched line", expect = "number" },
  { template = "*-B* _NUM_", description = "Print _NUM_ lines before the matched line", expect = "number" },
  { template = "-r", description = "Search files recursively" },
]

[[commands]]
template = "find _PATH_ _EXPRESSION_"
description = "Find files or directories (*find*)"

groups.PATH.expect = "path"
groups.EXPRESSION.flags = [
  { template = "*-iname* _PATTERN_", description = "File name pattern (e.g '*one*')", expect = "string" },
]

[[commands]]
template = "git config [_OPTIONS_] user.email _EMAIL_"
description = "Set git email address (*git*)"

groups.EMAIL.expect = "path"
groups.OPTIONS.flags = [
  { template = "--global", description = " Write to global *~/.gitconfig* file rather than the repository *.git/config*" },
]

[[commands]]
# This is a command template. Arguments in square brackets mean they are optional.
template = "curl [_OPTIONS_] _URL_"
# A command description.
description = "Send an HTTP request (*curl*)"

# Specify which values to accept (string/number/path)
groups.URL.expect = "string"
# OPTIONS group expects flags
groups.OPTIONS.flags = [
  # Define a flag template. A template can either include an argument or not.
  # If you specified an argument then you can set which values an argument can expect (string/number/path).
  # Set multiple to true if this flag could be specified more than once.
  # Set suggest to a list of suggested options. Note, that user can still specify a custom option. These values are mostly for guidance and help.
  { template = "*-H* _VALUE_", description = "Include a header (e.g -H \"Content-Type: application/json\")", expect = "string", multiple = true },
  { template = "*-X* _METHOD_", description = "Set a request method", expect = "string", suggest = ["GET", "POST", "PUT", "DELETE", "HEAD", "PATCH"]  },
  { template = "-v", description = "Verbose logging" },
  { template = "*-d* _DATA_", description = "Set request payload (use '@myfile.txt' to read data from file)", expect = "string" },
  { template = "-L", description = "Follow redirects" },
]
